import type { Metadata } from "next";
import { ServicesPage, servicesMetadata } from "@/components/locale-pages/SimplePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = servicesMetadata("fr");

export default function Page() {
  return <ServicesPage locale="fr" />;
}
