import type { Metadata } from "next";
import { CollectionPage, collectionMetadata, collectionParams } from "@/components/locale-pages/CollectionPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ collection: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return collectionParams();
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { collection } = await params;
  return collectionMetadata("de", collection);
}

export default async function Page({ params }: Props) {
  const { collection } = await params;
  return <CollectionPage locale="de" slug={collection} />;
}
