import { localeFeedResponse } from "@/lib/locale-feed-xml";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
/** /de/feed.xml — this locale's guides and news, for Google Discover and its Search Console property. */
export const dynamic = "force-static";

export function GET(): Response {
  return localeFeedResponse("de");
}
