import type { Metadata } from "next";
import { ProjectsIndexPage, projectsIndexMetadata } from "@/components/locale-pages/ProjectPages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = projectsIndexMetadata("fr");

export default function Page() {
  return <ProjectsIndexPage locale="fr" />;
}
