import type { Metadata } from "next";
import { MarketContact } from "@/components/market/MarketContact";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("tr", "/contact");

export default function MarketContactPage() {
  return <MarketContact locale="tr" />;
}
