import type { Metadata } from "next";
import { NewsArticlePage, newsArticleMetadata, newsParams } from "@/components/locale-pages/ArticlePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ slug: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return newsParams();
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  return newsArticleMetadata("de", slug);
}

export default async function Page({ params }: Props) {
  const { slug } = await params;
  return <NewsArticlePage locale="de" slug={slug} />;
}
