import type { Metadata } from "next";
import { ConfiguratorStudioPage, configuratorStudioMetadata } from "@/components/locale-pages/ConfiguratorStudioPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = configuratorStudioMetadata("fr");

export default function Page() {
  return <ConfiguratorStudioPage locale="fr" />;
}
