import type { Metadata } from "next";
import { NewsIndexPage, newsIndexMetadata } from "@/components/locale-pages/ArticlePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = newsIndexMetadata("tr");

export default function Page() {
  return <NewsIndexPage locale="tr" />;
}
