import type { Metadata } from "next";
import { MarketCompany } from "@/components/market/MarketCompany";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("tr", "/company");

export default function MarketCompanyPage() {
  return <MarketCompany locale="tr" />;
}
