import type { Metadata } from "next";
import { MarketCertifications } from "@/components/market/MarketCertifications";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("ru", "/certifications");

export default function MarketCertificationsPage() {
  return <MarketCertifications locale="ru" />;
}
