import type { Metadata } from "next";
import { MarketProducts } from "@/components/market/MarketProducts";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("fr", "/products");

export default function MarketProductsPage() {
  return <MarketProducts locale="fr" />;
}
