import type { Metadata } from "next";
import { ComparePage, compareMetadata, compareParams } from "@/components/locale-pages/ComparePage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ category: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return compareParams();
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { category } = await params;
  return compareMetadata("tr", category);
}

export default async function Page({ params }: Props) {
  const { category } = await params;
  return <ComparePage locale="tr" slug={category} />;
}
