import type { Metadata } from "next";
import { ContactPage, contactMetadata } from "@/components/locale-pages/ContactPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = contactMetadata("ar");

export default function Page() {
  return <ContactPage locale="ar" />;
}
