import type { Metadata } from "next";
import { ProductsIndexPage, productsIndexMetadata } from "@/components/locale-pages/ProductsIndexPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = productsIndexMetadata("de");

export default function Page() {
  return <ProductsIndexPage locale="de" />;
}
