import type { Metadata } from "next";
import { ConfiguratorPage, configuratorMetadata } from "@/components/locale-pages/ConfiguratorPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = configuratorMetadata("fr");

export default function Page() {
  return <ConfiguratorPage locale="fr" />;
}
