import type { Metadata } from "next";
import { MarketFaq } from "@/components/market/MarketFaq";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("ru", "/faq");

export default function MarketFaqPage() {
  return <MarketFaq locale="ru" />;
}
