import { localeSitemapResponse } from "@/lib/locale-sitemap-xml";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
/** /ko/sitemap.xml — this locale's slice of /sitemap.xml, for its Search Console property. */
export const dynamic = "force-static";

export function GET(): Response {
  return localeSitemapResponse("ko");
}
