import type { Metadata } from "next";
import { ProductStudiesPage, productStudiesMetadata } from "@/components/locale-pages/SimplePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = productStudiesMetadata("tr");

export default function Page() {
  return <ProductStudiesPage locale="tr" />;
}
