import type { Metadata } from "next";
import { FaqPage, faqMetadata } from "@/components/locale-pages/FaqPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = faqMetadata("ko");

export default function Page() {
  return <FaqPage locale="ko" />;
}
