import type { Metadata } from "next";
import { DownloadsPage, downloadsMetadata } from "@/components/locale-pages/DownloadsPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = downloadsMetadata("de");

export default function Page() {
  return <DownloadsPage locale="de" />;
}
