import type { Metadata } from "next";
import { ProjectPage, projectMetadata, projectParams } from "@/components/locale-pages/ProjectPages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ slug: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return projectParams();
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  return projectMetadata("ja", slug);
}

export default async function Page({ params }: Props) {
  const { slug } = await params;
  return <ProjectPage locale="ja" slug={slug} />;
}
