import { articleFeedResponse } from "@/lib/article-feed";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
/** /tr/feed.xml — this locale's guides and news, for Google Discover and its Search Console property. */
export const dynamic = "force-static";

export function GET(): Response {
  return articleFeedResponse("tr");
}
