"use client";

import type { FocusEvent, PointerEvent, TransitionEvent } from "react";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLink } from "@/components/site/ArrowLink";
import { cn } from "@/lib/utils";
import {
  getNextSlideIndex,
  getRenderedSlideIndexes,
  shouldConserveBandwidth,
  shouldAutoplay,
} from "@/lib/carousel";
import type { HeroCarouselContent } from "@/types/fsb-modules";
import { getResponsiveEditorialImageProps } from "./editorial-images";

/** Widths generated by scripts/build-mobile-hero-crops.mjs. Mirrored there. */
const MOBILE_HERO_WIDTHS = [400, 800];

/**
 * The 4:3 crops of a slide, for the phone frame that is 4:3.
 *
 * Returns candidates only; if the files are absent the `<source>` simply fails to match
 * anything useful and the panorama below it is used — which is the old behaviour, not a
 * broken page. `build-mobile-hero-crops.mjs --check` runs in `test:export` so that
 * fallback never ships silently.
 */
function mobileHeroSrcSet(src: string): string {
  const stem = src.slice(src.lastIndexOf("/") + 1).replace(/\.webp$/i, "");
  return MOBILE_HERO_WIDTHS.map(
    (width) => `/images/editorial/mobile-hero/${stem}-${width}w-4x3.webp ${width}w`,
  ).join(", ");
}

interface HeroCarouselProps {
  content: HeroCarouselContent;
}

const STAGE_DELAY_MS = 3000;
const DISPLAY_INTERVAL_MS = 6000;
const TRANSITION_SAFETY_MS = 2000;

export function HeroCarousel({ content }: HeroCarouselProps) {
  const [activeIndex, setActiveIndex] = useState(0);
  const [hovered, setHovered] = useState(false);
  const [focusWithin, setFocusWithin] = useState(false);
  const [documentHidden, setDocumentHidden] = useState(false);
  const [reducedMotion, setReducedMotion] = useState(false);
  const [conserveData, setConserveData] = useState(false);
  const [stagedIndex, setStagedIndex] = useState<number | null>(null);
  const [leavingIndex, setLeavingIndex] = useState<number | null>(null);
  const [activeReady, setActiveReady] = useState(false);
  const pointerStart = useRef<number | null>(null);
  const loadedIndexes = useRef(new Set<number>());
  const pendingTarget = useRef<number | null>(null);
  const transitionInProgress = useRef(false);
  const activationFrames = useRef<number[]>([]);
  const stageTimer = useRef<number | null>(null);
  const advanceTimer = useRef<number | null>(null);
  const transitionFallbackTimer = useRef<number | null>(null);
  const slideCount = content.slides.length;

  useEffect(() => {
    const mediaQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
    const sync = () => setReducedMotion(mediaQuery.matches);
    sync();
    mediaQuery.addEventListener("change", sync);
    return () => mediaQuery.removeEventListener("change", sync);
  }, []);

  useEffect(() => {
    const sync = () => setDocumentHidden(document.hidden);
    sync();
    document.addEventListener("visibilitychange", sync);
    return () => document.removeEventListener("visibilitychange", sync);
  }, []);

  useEffect(() => {
    const connection = (
      navigator as Navigator & {
        connection?: {
          saveData?: boolean;
          effectiveType?: string;
          addEventListener?: (type: "change", listener: () => void) => void;
          removeEventListener?: (type: "change", listener: () => void) => void;
        };
      }
    ).connection;
    const sync = () => setConserveData(shouldConserveBandwidth(connection));

    sync();
    connection?.addEventListener?.("change", sync);
    return () => connection?.removeEventListener?.("change", sync);
  }, []);

  const cancelActivationFrames = useCallback(() => {
    for (const frame of activationFrames.current) {
      window.cancelAnimationFrame(frame);
    }
    activationFrames.current = [];
  }, []);

  useEffect(() => cancelActivationFrames, [cancelActivationFrames]);

  const clearAutoplayTimers = useCallback(() => {
    if (stageTimer.current !== null) window.clearTimeout(stageTimer.current);
    if (advanceTimer.current !== null) window.clearTimeout(advanceTimer.current);
    stageTimer.current = null;
    advanceTimer.current = null;
  }, []);

  const finishTransition = useCallback(() => {
    if (transitionFallbackTimer.current !== null) {
      window.clearTimeout(transitionFallbackTimer.current);
      transitionFallbackTimer.current = null;
    }
    setLeavingIndex(null);
    transitionInProgress.current = false;
  }, []);

  useEffect(
    () => () => {
      if (transitionFallbackTimer.current !== null) {
        window.clearTimeout(transitionFallbackTimer.current);
      }
    },
    [],
  );

  useEffect(() => {
    // A live OS preference change cancels CSS transitions. Complete the state
    // change explicitly because cancelled transitions do not reliably emit
    // `transitionend` in every browser.
    if (!reducedMotion || (leavingIndex === null && !transitionInProgress.current)) {
      return;
    }

    const frame = window.requestAnimationFrame(() => {
      cancelActivationFrames();
      setStagedIndex(null);
      pendingTarget.current = null;
      finishTransition();
    });
    return () => window.cancelAnimationFrame(frame);
  }, [cancelActivationFrames, finishTransition, leavingIndex, reducedMotion]);

  const beginTransition = useCallback(
    (targetIndex: number) => {
      if (
        transitionInProgress.current ||
        targetIndex === activeIndex ||
        targetIndex < 0 ||
        targetIndex >= slideCount
      ) {
        return;
      }

      transitionInProgress.current = true;
      pendingTarget.current = null;
      setStagedIndex(null);
      setActiveReady(loadedIndexes.current.has(targetIndex));

      if (reducedMotion) {
        setLeavingIndex(null);
        setActiveIndex(targetIndex);
        transitionInProgress.current = false;
        return;
      }

      setLeavingIndex(activeIndex);
      setActiveIndex(targetIndex);
      transitionFallbackTimer.current = window.setTimeout(
        finishTransition,
        TRANSITION_SAFETY_MS,
      );
    },
    [activeIndex, finishTransition, reducedMotion, slideCount],
  );

  const activateStagedSlide = useCallback(
    (targetIndex: number) => {
      cancelActivationFrames();
      const firstFrame = window.requestAnimationFrame(() => {
        const secondFrame = window.requestAnimationFrame(() => {
          activationFrames.current = [];
          beginTransition(targetIndex);
        });
        activationFrames.current.push(secondFrame);
      });
      activationFrames.current.push(firstFrame);
    },
    [beginTransition, cancelActivationFrames],
  );

  const markSlideLoaded = useCallback(
    (index: number) => {
      loadedIndexes.current.add(index);
      if (index === activeIndex) setActiveReady(true);
      if (pendingTarget.current === index) activateStagedSlide(index);
    },
    [activeIndex, activateStagedSlide],
  );

  useEffect(() => {
    if (
      !activeReady ||
      leavingIndex !== null ||
      !shouldAutoplay({
        isHovered: hovered,
        isFocused: focusWithin,
        isDocumentHidden: documentHidden,
        reducedMotion,
        conserveData,
      }) ||
      slideCount < 2
    ) {
      return;
    }

    const targetIndex = getNextSlideIndex(activeIndex, slideCount, 1);
    stageTimer.current = window.setTimeout(() => {
      setStagedIndex(targetIndex);
    }, STAGE_DELAY_MS);
    advanceTimer.current = window.setTimeout(() => {
      pendingTarget.current = targetIndex;
      setStagedIndex(targetIndex);
      if (loadedIndexes.current.has(targetIndex)) {
        activateStagedSlide(targetIndex);
      }
    }, DISPLAY_INTERVAL_MS);

    return clearAutoplayTimers;
  }, [
    activeIndex,
    activeReady,
    activateStagedSlide,
    clearAutoplayTimers,
    conserveData,
    documentHidden,
    focusWithin,
    hovered,
    leavingIndex,
    reducedMotion,
    slideCount,
  ]);

  const requestSlide = (delta: number) => {
    if (slideCount < 2 || transitionInProgress.current) return;
    clearAutoplayTimers();
    const targetIndex = getNextSlideIndex(activeIndex, slideCount, delta);
    pendingTarget.current = targetIndex;
    setStagedIndex(targetIndex);
    if (loadedIndexes.current.has(targetIndex)) {
      activateStagedSlide(targetIndex);
    }
  };

  const previous = () => requestSlide(-1);
  const next = () => requestSlide(1);

  const handleBlur = (event: FocusEvent<HTMLElement>) => {
    if (!event.currentTarget.contains(event.relatedTarget)) {
      setFocusWithin(false);
    }
  };

  const handlePointerUp = (event: PointerEvent<HTMLDivElement>) => {
    if (pointerStart.current === null) return;
    const distance = event.clientX - pointerStart.current;
    pointerStart.current = null;
    if (Math.abs(distance) < 48) return;
    if (distance > 0) previous();
    else next();
  };

  const handleSlideTransitionEnd = (
    index: number,
    event: TransitionEvent<HTMLDivElement>,
  ) => {
    if (
      index !== leavingIndex ||
      event.target !== event.currentTarget ||
      event.propertyName !== "opacity"
    ) {
      return;
    }

    finishTransition();
  };

  const renderedIndexes = getRenderedSlideIndexes({
    activeIndex,
    stagedIndex,
    leavingIndex,
    slideCount,
  });

  return (
    /*
      `layout` is load-bearing and was missing.

      This section previously carried `col-outset`, but its parent `.modules` is not a
      grid — it only manages vertical rhythm — so the band class resolved to nothing and
      the carousel ran edge to edge, caption included. Establishing the grid here puts
      both the image and the caption on the content band, which is where every other
      module on the page sits and which gives the hero the margins the reference has.
    */
    <section
      aria-label={content.ariaLabel}
      aria-roledescription="carousel"
      className="layout"
      onBlur={handleBlur}
      onFocus={() => setFocusWithin(true)}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <div
        className="col-content relative aspect-[4/3] touch-pan-y overflow-hidden bg-surface-alt xs:aspect-[1920/754]"
        onPointerDown={(event) => {
          pointerStart.current = event.clientX;
        }}
        onPointerUp={handlePointerUp}
      >
        {renderedIndexes.map((index) => {
          const slide = content.slides[index];
          const responsive = slide.media.src
            ? getResponsiveEditorialImageProps(
                slide.media.src,
                // Below `xs` the frame is 4:3 while the source is ~2.55:1. The
                // object-cover crop therefore needs ~1.9x the frame width to
                // avoid upscaling the source vertically on phones.
                "(min-width: 1440px) 1376px, (min-width: 640px) 96vw, 184vw",
              )
            : null;
          const isInitialLcp =
            index === 0 && activeIndex === 0 && leavingIndex === null;

          return (
            <div
              aria-hidden={index !== activeIndex}
              data-active={index === activeIndex}
              // Timing, easing and the scale settle live in globals.css (.hero-slide).
              // Staging the incoming frame for one paint preserves a true crossfade.
              className={cn(
                "hero-slide absolute inset-0",
                index === activeIndex && "z-[1]",
              )}
              key={`${slide.title}-${index}`}
              onTransitionCancel={(event) =>
                handleSlideTransitionEnd(index, event)
              }
              onTransitionEnd={(event) => handleSlideTransitionEnd(index, event)}
            >
              {responsive && isInitialLcp ? (
                /*
                  TWO PRELOADS, EACH SCOPED TO THE VIEWPORT THAT WILL USE IT.

                  Lighthouse started reporting "LCP request discovery" the moment the
                  <picture> below lost its `fetchPriority="high"`, and it was right to:
                  the image the Largest Contentful Paint is measured on had nothing telling
                  the browser to start it early.

                  The reason it lost that attribute is in the comment on the img — React
                  hoists ONE preload built from the img's own srcset, which knows nothing
                  about the `<source media>` above it, so the phone downloaded the panorama
                  it was never going to show AND the crop it did show: 64 KB where 43 had
                  been.

                  `ReactDOM.preload()` cannot express this — its options have no `media`.
                  A rendered <link> can, and React 19 hoists it into <head> from here. So
                  each viewport preloads exactly the file its own <source> will select, and
                  neither downloads the other's.

                  Only on the initial LCP slide: preloading all four would be four
                  high-priority images competing for the one that is actually visible.
                */
                <>
                  <link
                    as="image"
                    fetchPriority="high"
                    imageSizes="100vw"
                    imageSrcSet={mobileHeroSrcSet(slide.media.src ?? "")}
                    media="(max-width: 639px)"
                    rel="preload"
                  />
                  {responsive.srcSet ? (
                    <link
                      as="image"
                      fetchPriority="high"
                      imageSizes={responsive.sizes}
                      imageSrcSet={responsive.srcSet}
                      media="(min-width: 640px)"
                      rel="preload"
                    />
                  ) : null}
                </>
              ) : null}
              {responsive ? (
                /*
                  A <picture> so the phone gets a picture shaped like the hole it goes in.

                  Measured on the production export at 375×812: the frame renders
                  343 × 257 CSS px and the browser correctly fetched the 1600w panorama,
                  43 KB, because `object-cover` has to scale a 2.55:1 source until its
                  height covers a 4:3 box — about 1.9× the frame's width, which is what
                  the `sizes` hint below says. Half of those bytes were then cropped off
                  the sides and never seen. The mobile source below is that same centred
                  crop, done once at build time: 21 KB instead of 43, on the image the
                  Largest Contentful Paint is measured on.

                  Above 640px the frame is `aspect-[1920/754]`, near the source's own
                  shape, so the media query stops and the panorama is served intact.
                  See scripts/build-mobile-hero-crops.mjs.
                */
                <picture>
                  <source
                    media="(max-width: 639px)"
                    sizes="100vw"
                    srcSet={mobileHeroSrcSet(slide.media.src ?? "")}
                    type="image/webp"
                  />
                  <img
                    {...responsive}
                    alt={slide.media.label}
                    className="absolute inset-0 h-full w-full object-cover"
                    decoding="async"
                    /*
                      NO `fetchPriority="high"` — removed 2026-09-15, and the reason is
                      specific to the <picture> above rather than a change of mind about
                      priority.

                      React hoists a `<link rel="preload" as="image">` for a high-priority
                      image, and that preload is built from THIS img's srcset. It knows
                      nothing about the `<source media="(max-width: 639px)">`. So the phone
                      fetched the preloaded panorama AND then the mobile crop it actually
                      used: measured at 64 KB where it had been 43. The optimisation paid
                      for itself in the wrong direction.

                      Without it there is no preload and no duplicate. The image is still
                      the first element in the body and still `eager`, so the parser starts
                      it immediately; it just starts at normal priority. 21 KB fetched once
                      beats 43 KB preloaded plus 21 KB fetched.
                    */
                    loading={isInitialLcp ? "eager" : "lazy"}
                    onLoad={() => markSlideLoaded(index)}
                    ref={(element) => {
                      if (element?.complete && element.naturalWidth > 0) {
                        markSlideLoaded(index);
                      }
                    }}
                  />
                </picture>
              ) : null}
            </div>
          );
        })}

        {/*
          Manual controls removed on request: the strip of arrows and dots read as
          clutter against a full-bleed image. The carousel now advances on its own.
          Autoplay still pauses on hover, on focus, when the tab is hidden, and under
          prefers-reduced-motion — so it is not a trap for anyone reading the caption.
        */}
      </div>

      <div aria-live="polite" className="col-content grid w-full grid-cols gap-x pb-32 pt-16 md:pb-48 md:pt-24">
        {content.slides.map((slide, index) => (
          <div
            aria-hidden={index !== activeIndex}
            className="hero-caption-slide col-span-full row-start-1 grid grid-cols-subgrid gap-x gap-y-16"
            data-active={index === activeIndex}
            inert={index !== activeIndex}
            key={`${slide.title}-${index}`}
          >
            <div className="col-span-full md:col-span-5 xl:col-span-6">
              <h2 className="text-h3 font-semibold">{slide.title}</h2>
              <p className="mt-4 max-w-[36rem] text-c1">{slide.body}</p>
            </div>
            <div className="col-span-full md:[grid-column:span_3/-1] xl:[grid-column:span_6/-1]">
              <ArrowLink href={slide.href} prefetch={false}>
                {slide.linkLabel}
              </ArrowLink>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
