import type { Locale } from "@/data/site";
import sheets from "@/data/generated/spec-sheets.json";

/*
  One-page PDF spec sheet, generated by scripts/build_spec_sheets.py only for products whose
  published data is enough to send (see docs/research/spec-sheet-gaps.md). The sheets are
  English, so the link says so on es / pt, and the seven overlay locales show nothing until
  their own label exists.
*/
const AVAILABLE = new Set<string>(sheets);

const LABEL: Partial<Record<Locale, string>> = {
  en: "Download the spec sheet (PDF)",
  es: "Descargar la ficha técnica (PDF, en inglés)",
  pt: "Baixar a ficha técnica (PDF, em inglês)",
};

export function ProductSpecSheetLink({ slug, locale }: { slug: string; locale: Locale }) {
  const label = LABEL[locale];
  if (!label || !AVAILABLE.has(slug)) return null;
  return (
    <p className="mt-32 text-c1">
      <a
        href={`/downloads/spec-sheets/${slug}.pdf`}
        download
        className="text-ink underline underline-offset-4"
      >
        {label}
      </a>
    </p>
  );
}
