import type { Locale } from "@/data/site";
import sheets from "@/data/generated/spec-sheets.json";

/*
  One-page PDF spec sheet, generated by scripts/build_spec_sheets.py only for products whose
  published data is enough to send (see docs/research/spec-sheet-gaps.md). Every sheet exists
  in all ten languages: English at /downloads/spec-sheets/, the others under /<locale>/.
*/
const AVAILABLE = new Set<string>(sheets);

const LABEL: Record<Locale, string> = {
  en: "Download the spec sheet (PDF)",
  es: "Descargar la ficha técnica (PDF)",
  pt: "Baixar a ficha técnica (PDF)",
  fr: "Télécharger la fiche technique (PDF)",
  de: "Datenblatt herunterladen (PDF)",
  ja: "仕様書をダウンロード（PDF）",
  ko: "사양서 다운로드(PDF)",
  tr: "Teknik föyü indir (PDF)",
  ru: "Скачать техническую карту (PDF)",
  ar: "تنزيل ورقة المواصفات (PDF)",
};

export function ProductSpecSheetLink({ slug, locale }: { slug: string; locale: Locale }) {
  if (!AVAILABLE.has(slug)) return null;
  const label = LABEL[locale];
  return (
    <p className="mt-32 text-c1">
      <a
        href={`/downloads/spec-sheets/${locale === "en" ? "" : `${locale}/`}${slug}.pdf`}
        download
        className="short-marker short-marker-compact"
      >
        {label}
      </a>
    </p>
  );
}
