import type { Metadata } from "next";
import { GuideArticlePage, guideArticleMetadata, guideParams } from "@/components/locale-pages/ArticlePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ slug: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return guideParams("ru");
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  return guideArticleMetadata("ru", slug);
}

export default async function Page({ params }: Props) {
  const { slug } = await params;
  return <GuideArticlePage locale="ru" slug={slug} />;
}
