import type { Metadata } from "next";
import { ProductPage, productMetadata, productParams } from "@/components/locale-pages/ProductPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ category: string; slug: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return productParams();
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { category, slug } = await params;
  return productMetadata("ko", category, slug);
}

export default async function Page({ params }: Props) {
  const { category, slug } = await params;
  return <ProductPage locale="ko" category={category} slug={slug} />;
}
