import type { Metadata } from "next";
import { CompanyPage, companyMetadata } from "@/components/locale-pages/SimplePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = companyMetadata("ko");

export default function Page() {
  return <CompanyPage locale="ko" />;
}
