import type { Metadata } from "next";
import { CategoryPage, categoryMetadata, categoryParams } from "@/components/locale-pages/CategoryPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
type Props = { params: Promise<{ category: string }> };

export const dynamicParams = false;

export function generateStaticParams() {
  return categoryParams();
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { category } = await params;
  return categoryMetadata("ar", category);
}

export default async function Page({ params }: Props) {
  const { category } = await params;
  return <CategoryPage locale="ar" slug={category} />;
}
