import type { Metadata } from "next";
import { CylinderCalculatorPage, cylinderCalculatorMetadata } from "@/components/locale-pages/CylinderCalculatorPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = cylinderCalculatorMetadata("ru");

export default function Page() {
  return <CylinderCalculatorPage locale="ru" />;
}
