import type { Metadata } from "next";
import { MarketServices } from "@/components/market/MarketServices";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("ar", "/services");

export default function MarketServicesPage() {
  return <MarketServices locale="ar" />;
}
