import type { Metadata } from "next";
import { JohnsonLiuPage, johnsonLiuMetadata } from "@/components/locale-pages/SimplePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = johnsonLiuMetadata("ko");

export default function Page() {
  return <JohnsonLiuPage locale="ko" />;
}
