import type { Metadata } from "next";
import { GlossaryPage, glossaryMetadata } from "@/components/locale-pages/GlossaryPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = glossaryMetadata("de");

export default function Page() {
  return <GlossaryPage locale="de" />;
}
