import type { Metadata } from "next";
import { ModelLookupPage, modelLookupMetadata } from "@/components/locale-pages/ModelLookupPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = modelLookupMetadata("ar");

export default function Page() {
  return <ModelLookupPage locale="ar" />;
}
