import type { Metadata } from "next";
import { MarketHome } from "@/components/market/MarketHome";
import { marketPageMetadata } from "@/lib/market";

/** GENERATED by scripts/scaffold-market-routes.mjs — edit the template there. */
export const metadata: Metadata = marketPageMetadata("ru", "/");

export default function MarketHomePage() {
  return <MarketHome locale="ru" />;
}
