import type { Metadata } from "next";
import { archivo } from "../fonts";
import "../globals.css";
import { JsonLd, organisationSchema, websiteSchema } from "@/components/site/JsonLd";
import { Analytics, AnalyticsHead } from "@/components/site/Analytics";
import { indexable, siteName, siteUrl } from "@/data/site";
import { marketLocaleMeta } from "@/data/market-locales";
import { marketCopy, marketPageMetadata } from "@/lib/market";

/**
 * GENERATED by scripts/scaffold-market-routes.mjs — edit the template there, not this file.
 *
 * The ar market tree. One root layout per locale, like /es and /pt, because
 * <html lang> and dir are decided here and a shared root cannot express ten of them.
 */
const LOCALE = "ar" as const;
const meta = marketLocaleMeta[LOCALE];

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  applicationName: siteName,
  ...marketPageMetadata(LOCALE, "/"),
  /* Page titles supply only their own name; the brand suffix is appended here. */
  title: {
    default: `${marketCopy[LOCALE].meta["/"].title} | ${siteName}`,
    template: `%s | ${siteName}`,
  },
  robots: indexable
    ? { index: true, follow: true, googleBot: { index: true, follow: true, "max-image-preview": "large" } }
    : { index: false, follow: false },
};

export default function MarketRootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang={meta.htmlLang}
      dir={meta.dir}
      suppressHydrationWarning
      className={`h-full antialiased ${archivo.variable}`}
    >
      <head>
        <AnalyticsHead />
        <JsonLd data={organisationSchema()} />
        <JsonLd data={websiteSchema()} />
      </head>
      <body suppressHydrationWarning className="flex min-h-full flex-col">
        {/* Header and footer are rendered by each page (MarketMain), which knows which
            page it is; a layout cannot, and the language menu needs to. */}
        <div className="flex min-h-screen flex-col justify-between">{children}</div>
        <Analytics />
      </body>
    </html>
  );
}
