import type { Metadata } from "next";
import type { Locale } from "@/data/locales";
import { tx } from "@/lib/i18n";
import { pageMetadata } from "@/lib/seo";

/**
 * Helpers shared by the locale page components in this directory.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS DIRECTORY IS
 *
 * The English routes under src/app/(en) carry their page copy inline, and the Spanish and
 * Portuguese routes are hand-written copies of them with translated copy. That stops
 * scaling at three: the seven overlay locales (fr de ja ko tr ru ar, 2026-09-25) share
 * ONE implementation of each page, here, parametrised by locale. Every sentence goes
 * through `tx(locale, "English sentence")`, which reads content/i18n/<code>/ui.json
 * and falls back to English visibly; every link goes through `p()` so it stays in the
 * reader's tree. The route files under src/app/<code>/ are generated by
 * scripts/scaffold-locale-routes.mjs and are five lines each.
 *
 * The English, Spanish and Portuguese routes are NOT rewired to these components — they
 * are the client's approved copy and the copy session's territory. The components are
 * written from the English routes sentence for sentence, so the seven trees render the
 * same page, in their own language, with the same structure.
 */

/** "/products" → "/de/products/" — the reader's tree, trailing slash as next.config wants. */
export function prefixer(locale: Locale) {
  return (path: string): string => {
    const clean = path === "/" ? "" : `/${path.replace(/^\/|\/$/g, "")}`;
    const query = "";
    return locale === "en" ? `${clean}/${query}` || "/" : `/${locale}${clean}/${query}`;
  };
}

/** `p("/contact", "?subject=x")` — a prefixed path with a query string kept intact. */
export function withQuery(href: string, query: string): string {
  return `${href}${query.startsWith("?") ? query : `?${query}`}`;
}

/** Metadata for a static page of the tree, with the title and description translated. */
export function localeMetadata(
  locale: Locale,
  enPath: string,
  title: string,
  description: string,
  extra?: { image?: string; imageAlt?: string },
): Metadata {
  return pageMetadata({
    enPath,
    locale,
    title: tx(locale, title),
    description: tx(locale, description),
    ...(extra ?? {}),
  });
}

/** Lower-case a translated name the way the English pages do, safely for every script. */
export function lower(value: string, locale: Locale): string {
  /* German nouns keep their capital; Japanese, Korean and Arabic have no case. */
  if (locale === "de" || locale === "ja" || locale === "ko" || locale === "ar") return value;
  return value.toLowerCase();
}
