import type { Metadata } from "next";
import { CertificationsPage, certificationsMetadata } from "@/components/locale-pages/CertificationsPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = certificationsMetadata("fr");

export default function Page() {
  return <CertificationsPage locale="fr" />;
}
