import type { Metadata } from "next";
import { FinishesPage, finishesMetadata } from "@/components/locale-pages/FinishesPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = finishesMetadata("ja");

export default function Page() {
  return <FinishesPage locale="ja" />;
}
