import type { Metadata } from "next";
import { ProductFinderPage, productFinderMetadata } from "@/components/locale-pages/ProductFinderPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = productFinderMetadata("de");

export default function Page() {
  return <ProductFinderPage locale="de" />;
}
