import type { Metadata } from "next";
import { archivo } from "../fonts";
import "../globals.css";
import { SiteHeader } from "@/components/site/SiteHeader";
import { getMenuCategories } from "@/data/categories";
import { SiteFooter } from "@/components/site/SiteFooter";
import { LazyPromoDialog } from "@/components/site/LazyPromoDialog";
import { LanguageSuggestion } from "@/components/site/LanguageSuggestion";
import { JsonLd, organisationSchema, websiteSchema } from "@/components/site/JsonLd";
import { Analytics, AnalyticsHead } from "@/components/site/Analytics";
import { absoluteUrl, defaultDescription, defaultTitle, indexable, siteName, siteUrl } from "@/data/site";
import { LOCALE_DIR, LOCALE_TAG, OG_LOCALE } from "@/lib/i18n";
import { alternateLanguages } from "@/lib/seo";
import { I18nClientBundle } from "@/data/generated/i18n-client/ko";
import clientBundle from "@/data/generated/i18n-client/ko.json" with { type: "json" };
import { registerClientBundle } from "@/lib/i18n-client";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
const LOCALE = "ko" as const;
/*
  Register the dictionary in THIS module graph as well. <I18nClientBundle /> below registers
  it in the client/SSR layer, but Next evaluates a separate instance of src/lib/i18n-client.ts
  for server components; a server-rendered ProductCard (home page, related products) read an
  empty registry and printed "Stainless Steel" and "Model" on every overlay locale (2026-09-27).
*/
registerClientBundle(LOCALE, clientBundle);

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: defaultTitle[LOCALE],
    template: `%s | ${siteName}`,
  },
  description: defaultDescription[LOCALE],
  applicationName: siteName,
  alternates: {
    canonical: `/${LOCALE}/`,
    languages: alternateLanguages("/"),
  },
  openGraph: {
    type: "website",
    siteName,
    locale: OG_LOCALE[LOCALE],
    url: absoluteUrl(`/${LOCALE}/`),
    title: defaultTitle[LOCALE],
    description: defaultDescription[LOCALE],
    images: [
      {
        url: absoluteUrl("/images/editorial/home-panic-exit-bars.webp"),
        width: 2400,
        height: 943,
        alt: "HYDE",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle[LOCALE],
    description: defaultDescription[LOCALE],
    images: [absoluteUrl("/images/editorial/home-panic-exit-bars.webp")],
  },
  robots: indexable
    ? { index: true, follow: true, "max-image-preview": "large", googleBot: { index: true, follow: true, "max-image-preview": "large" } }
    : { index: false, follow: false },
};

export default function LocaleRootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang={LOCALE_TAG[LOCALE]}
      dir={LOCALE_DIR[LOCALE]}
      suppressHydrationWarning
      className={`h-full antialiased ${archivo.variable}`}
    >
      <head>
        {/* This locale's RSS, so Discover and readers find the ko articles, not the English ones. */}
        <link rel="alternate" type="application/rss+xml" title="HYDE — ko" href="/ko/feed.xml" />
        <AnalyticsHead />
        <JsonLd data={organisationSchema()} />
        <JsonLd data={websiteSchema()} />
      </head>
      <body suppressHydrationWarning className="flex min-h-full flex-col">
        {/* This locale's client dictionary — one chunk, this locale only (src/lib/i18n-client.ts). */}
        <I18nClientBundle />
        {/* Above the header and in flow: it offers, it never covers. See the component. */}
        <LanguageSuggestion />
        <div className="flex min-h-screen flex-col justify-between">
          <SiteHeader categories={getMenuCategories()} />
          {children}
          <SiteFooter locale={LOCALE} />
        </div>
        <LazyPromoDialog />
        <Analytics />
      </body>
    </html>
  );
}
