import type { Metadata } from "next";
import { HomePage, homeMetadata } from "@/components/locale-pages/HomePage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = homeMetadata("tr");

export default function Page() {
  return <HomePage locale="tr" />;
}
