import type { Metadata } from "next";
import { DocumentsPage, documentsMetadata } from "@/components/locale-pages/DocumentsPage";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = documentsMetadata("ko");

export default function Page() {
  return <DocumentsPage locale="ko" />;
}
