import type { Metadata } from "next";
import { GuidesIndexPage, guidesIndexMetadata } from "@/components/locale-pages/ArticlePages";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = guidesIndexMetadata("fr");

export default function Page() {
  return <GuidesIndexPage locale="fr" />;
}
