import type { Metadata } from "next";
import { ArgentinaAr4Page, argentinaAr4Metadata } from "@/components/locale-pages/ArgentinaAr4Page";

/** GENERATED by scripts/scaffold-locale-routes.mjs — edit the template there, not this file. */
export const metadata: Metadata = argentinaAr4Metadata("fr");

export default function Page() {
  return <ArgentinaAr4Page locale="fr" />;
}
